# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
	languageCode = "en"
	languageName = "English"
	contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
	title = "Kingdom Apprentices"
	weight = 1
			
[fr]
	languageCode = "fr"
	languageName = "French"
	contentDir = "content/fr"
	title = "Kingdom Apprentices"
	weight = 2
	[fr.menu]
		[[fr.menu.main]]
			name = "Formation d'apprenti"
			url = "01_apprentice-training"
			weight = 10
		[[fr.menu.main]]
			name = "Étude"
			url = "02_teaching"
			weight = 20
		[[fr.menu.main]]
			name = "Blog"
			url = "03_blog"
			weight = 30		
		[[fr.menu.main]]
			name = "Filtres à eau bio-sable"
			url = "04_bio-water-filters"
            weight = 40 		
		[[fr.menu.main]]
			name = "Ressources Kpelle"
			url = "kpelle-resources"
			weight = 50
		[[fr.menu.main]]
		  name = "Contactez-nous"
		  url = "#contact"
		  weight = 60
		[[fr.menu.main]]			
			name = "À propos"
			url = "#about"
			weight = 70
		[[fr.menu.main]]
		  name = "Plan du site"
		  url = "site-map"
		  weight = 100
# Uncomment the lines below to configure your website in a second language.
#[zh]
#  languageCode = "zh-Hans"
#  contentDir = "content/zh"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1