[Hugo Website Root]
   C:\Users\Stephen\Documents\Hugo\Sites
[Docx Root]
   C:\Users\Stephen\Documents\Hugo\Sites\Kingdom_Apprentices
[Docx Language]
   en
[Dotx Template Path]
   Kingdom-Apprentices_Styles.dotx
[Languages]
   [en]
[DateChanged]
   2024-02-20 12:08:30.669252