[Hugo Website Root]
   C:\Users\sjd\Documents\Hugo\Sites\Kingdom_Apprentices_git
[Docx Root]
   C:\Users\sjd\Documents\Church_Published
[Docx Language]
   en
[Dotx Template Path]
   Kingdom-Apprentices_Styles.dotx
[Languages]
   [en,fr]
[DateChanged]
   2024-03-26 10:11:51.705577