[Hugo Website Root]
   C:\Users\Stephen\Documents\Hugo\Sites\Kingdom_Apprentices
[Docx Root]
   C:\Users\Stephen\Documents\Church_Published
[Docx Language]
   en
[Dotx Template Path]
   Kingdom-Apprentices_Styles.dotx
[Languages]
   [en,fr]
[DateChanged]
   2024-02-19 18:06:03.909100